apiVersion: v1
kind: Service
metadata:
  name: flask-cpu-burner-service
  namespace: default-scaling   # or default-scaling
spec:
  type: NodePort
  selector:
    app: flask-cpu-burner
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080