apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flask-app-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: flask-app
  podMetricsEndpoints:
    - port: http-metrics
      interval: 10s
