prometheus:
  prometheusSpec:
    scrapeInterval: 5s
    evaluationInterval: 5s
    scrapeTimeout: 3s

    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}

    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
